// Google Fontsからwoff2(unicode-range分割)を取得してアプリに同梱するスクリプト。
// 実行: node scripts/fetch-fonts.mjs
// 出力: public/fonts/files/*.woff2 と public/fonts/fonts.css
// アプリのランタイムは外部通信しない(オフライン要件)。フォント追加時はFAMILIESを変更して再実行。

import { mkdir, writeFile, rm } from 'node:fs/promises';
import path from 'node:path';

const FAMILIES = [
  { family: 'Shippori Mincho B1', weights: [700] },
  { family: 'Zen Kaku Gothic New', weights: [400, 500, 700] },
];

// Chrome UAを名乗るとwoff2 + unicode-range分割のCSSが返る
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const outDir = path.resolve('public/fonts');
const filesDir = path.join(outDir, 'files');

const query = FAMILIES.map(
  (f) => `family=${f.family.replaceAll(' ', '+')}:wght@${f.weights.join(';')}`,
).join('&');
const cssUrl = `https://fonts.googleapis.com/css2?${query}&display=swap`;

const res = await fetch(cssUrl, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error(`CSS fetch failed: ${res.status}`);
const css = await res.text();

await rm(filesDir, { recursive: true, force: true });
await mkdir(filesDir, { recursive: true });

// @font-faceブロックごとにurl()をローカルパスへ書き換えつつダウンロード
const blocks = css.match(/@font-face\s*{[^}]*}/g) ?? [];
if (blocks.length === 0) throw new Error('No @font-face blocks found');

let rewritten = [];
let counters = new Map();
for (const block of blocks) {
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1] ?? 'unknown';
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? '400';
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!url) continue;
  const slug = family.toLowerCase().replaceAll(' ', '-');
  const key = `${slug}-${weight}`;
  const n = (counters.get(key) ?? 0) + 1;
  counters.set(key, n);
  const fileName = `${key}.${String(n).padStart(3, '0')}.woff2`;
  const fontRes = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!fontRes.ok) throw new Error(`Font fetch failed: ${url}`);
  await writeFile(path.join(filesDir, fileName), Buffer.from(await fontRes.arrayBuffer()));
  rewritten.push(block.replace(url, `/fonts/files/${fileName}`));
}

const header = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand */\n`;
await writeFile(path.join(outDir, 'fonts.css'), header + rewritten.join('\n'));

const total = [...counters.entries()].map(([k, v]) => `${k}: ${v} files`).join(', ');
console.log(`Done. ${rewritten.length} font files -> public/fonts/files/ (${total})`);
